Modal windows
jumperM4/windows pull request #1
Opened 2023-04-07 18:55 UTC by jumperM4

2023-04-07 19:10 UTC, andrey-kudinov requested changes
Хорошая работа 👍
Есть несколько моментов, которые можно улучшить
Посмотри пж в комментариях

2023-04-07 19:10 UTC, andrey-kudinov commented on src/js/modules/modals.js
> +      close = document.querySelector(closeSelector);
Старайся пж не использовать синтаксис чз запятую
Считается, что это сложнее для чтения кода

2023-04-07 19:10 UTC, andrey-kudinov commented on src/js/modules/modals.js
> +    const trigger = document.querySelectorAll(triggerSelector),
Хочу обратить твоё внимание на нейминг
В твоём случае здесь массив элементов, поэтому trigger**s**

2023-04-07 19:10 UTC, andrey-kudinov commented on src/js/modules/modals.js
> +      item.addEventListener("click", (e) => {
Здесь так же хотел бы обратить внимание на нейминг
Старайся пж придерживаться более говорящего неймига
Тогда код будет более читабельный
На сложный проектах это играет большую роль
```
triggers.forEach(trigger => ...
cards.forEach(card => ...
books.forEach(book => ...
```

2023-04-07 19:10 UTC, andrey-kudinov commented on src/js/modules/modals.js
> +    console.log(trigger, modal, close);
Старайся пж удалять консольки после дебага

2023-04-07 19:10 UTC, andrey-kudinov commented on src/js/modules/modals.js
> +        document.body.style.overflow = "";
```
modal.style.display = 'none';
document.body.style.overflow = '';
```
Эти две строчки повторяются несколько раз, вынеси пж их в отдельную функцию `closeModal` и переиспользуй её
Это будет соответствовать принципу [DRY](https://ru.wikipedia.org/wiki/Don’t_repeat_yourself)
Так же добавь пж закрытие модального окна по клавише `escape`

2023-04-07 19:10 UTC, andrey-kudinov commented on src/js/modules/modals.js
> +  }
Давай попробуем в этом проекте писать исключительно стрелочные функции
Во-первых, практика рефакторинга (довольно простого)
Во-вторых, на мой взгляд, это позволит лучше читать код, так как он будет последовательный
Всегда понятно что за функция будет вызвана, так как она до этого объявлена
Так же на мой взгляд это современнее

2023-04-08 08:54 UTC, jumperM4 commented on src/js/modules/modals.js
> +  }
А стрелочные функции везде внедрять? Например, bindModel и showModelByTime - не стрелочные.

2023-04-08 09:31 UTC, merged